#!/bin/python3

import os
from datetime import datetime

print(datetime.now().strftime('%a %d/%m/%Y %H:%M:%S'))

if os.environ.get('BLOCK_BUTTON'):
    from tkinter import Tk
    from tkcalendar import Calendar

    window = Tk()
    window.title('Calendar')
    window.attributes('-type', 'dialog')
    window.geometry('835x530')
    Calendar(window, selectmode='none', font='JetBrainsMonoNerdFont 30', showothermonthdays=False).pack()
    window.mainloop()
